### ISSUE TITLE
Oprava úkolu #1

### ISSUE THREAD

**Issue by tommander** [evahrad/Evina_prvni#1]
<p>Celkově velmi pěkné :) Graficky hezky sladěná stránka, v jednoduchosti je vskutku krása. Kód je poskládaný dobře, dovolím si však pár poznámek:</p>
<ul><li>Ubral bych opakované prázdné řádky (např. mezi &lt;body&gt; a &lt;header class="hlavicka"&gt;) nebo bych harmonizoval jejich počet.</li>
<li>Doporučil bych odsazovat cokoliv uvnitř &lt;body&gt;&lt;/body&gt; v podobném duchu, jako je tomu uvnitř &lt;head&gt;&lt;/head&gt;, odsazování je pak jednotné a orientace v kódu jednodušší.</li>
<li>Oddíl &lt;section&gt; je střídavě používán a nepoužíván. Doporučil bych jej využívat vždy a používat střídavě dvě různé třídy. Je to pak jednodušší třeba i pro Google a další automaty, aby pochopily lépe strukturu stránky.</li>
<li>Řádek 2: atribut &bdquo;lang&ldquo; v &lt;html&gt; říká, v jakém jazyce je stránka. Je tato stránka opravdu anglicky?</li>
<li>Řádek 16: jelikož je &lt;header&gt; na stránce jen jednou, není nutné pro něj dělat třídu &bdquo;hlavicka&ldquo;. Ale to jen spíš jen tip, na tomto bodu nikterak netrvám.</li>
<li>Řádky 38&ndash;42: doporučil bych pro každý odstavec využít &lt;p&gt;&lt;/p&gt; místo prostých odřádkování pomocí &lt;br&gt;. Značka &lt;p&gt; značí odstavec, takže je to v tomto případě, domnívám se, vhodnější.</li>
<li>Řádek 74: značka &lt;img&gt; je umístěna mimo &lt;li&gt;&lt;/li&gt;</li>
<li>Řádek 92: místo &bdquo;c&ldquo; bych doporučil využít symbol pro copyright.</li>
</ul>
<p>Prosím tedy o zapracování a jsem otevřen diskusi o jakémkoliv z předchozích bodů :)</p>

**Comment by evahrad** [comment]
Ahoj Tome, udělala jsem úpravy (včera), a udělala push. Doufám že dorazily už :-).

**Comment by tommander** [comment]
<p>Je to super, děkuji moc a gratulace, dobrá práce! 👍 😉 Úkol jsem již tedy ohodnotil a je označen jako odevzdaný :)</p>

**Comment by evahrad** [comment]
Děkuji :-)
